// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FakekubeletClient is the client API for Fakekubelet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FakekubeletClient interface {
	PatchPodStatus(ctx context.Context, in *PatchPodStatusMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PatchFuturePodStatus(ctx context.Context, in *PatchPodStatusMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fakekubeletClient struct {
	cc grpc.ClientConnInterface
}

func NewFakekubeletClient(cc grpc.ClientConnInterface) FakekubeletClient {
	return &fakekubeletClient{cc}
}

func (c *fakekubeletClient) PatchPodStatus(ctx context.Context, in *PatchPodStatusMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/fakekubelet.fakekubelet/PatchPodStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fakekubeletClient) PatchFuturePodStatus(ctx context.Context, in *PatchPodStatusMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/fakekubelet.fakekubelet/PatchFuturePodStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FakekubeletServer is the server API for Fakekubelet service.
// All implementations must embed UnimplementedFakekubeletServer
// for forward compatibility
type FakekubeletServer interface {
	PatchPodStatus(context.Context, *PatchPodStatusMsg) (*emptypb.Empty, error)
	PatchFuturePodStatus(context.Context, *PatchPodStatusMsg) (*emptypb.Empty, error)
	mustEmbedUnimplementedFakekubeletServer()
}

// UnimplementedFakekubeletServer must be embedded to have forward compatible implementations.
type UnimplementedFakekubeletServer struct {
}

func (UnimplementedFakekubeletServer) PatchPodStatus(context.Context, *PatchPodStatusMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchPodStatus not implemented")
}
func (UnimplementedFakekubeletServer) PatchFuturePodStatus(context.Context, *PatchPodStatusMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchFuturePodStatus not implemented")
}
func (UnimplementedFakekubeletServer) mustEmbedUnimplementedFakekubeletServer() {}

// UnsafeFakekubeletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FakekubeletServer will
// result in compilation errors.
type UnsafeFakekubeletServer interface {
	mustEmbedUnimplementedFakekubeletServer()
}

func RegisterFakekubeletServer(s grpc.ServiceRegistrar, srv FakekubeletServer) {
	s.RegisterService(&Fakekubelet_ServiceDesc, srv)
}

func _Fakekubelet_PatchPodStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchPodStatusMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FakekubeletServer).PatchPodStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fakekubelet.fakekubelet/PatchPodStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FakekubeletServer).PatchPodStatus(ctx, req.(*PatchPodStatusMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fakekubelet_PatchFuturePodStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchPodStatusMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FakekubeletServer).PatchFuturePodStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fakekubelet.fakekubelet/PatchFuturePodStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FakekubeletServer).PatchFuturePodStatus(ctx, req.(*PatchPodStatusMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Fakekubelet_ServiceDesc is the grpc.ServiceDesc for Fakekubelet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fakekubelet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fakekubelet.fakekubelet",
	HandlerType: (*FakekubeletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatchPodStatus",
			Handler:    _Fakekubelet_PatchPodStatus_Handler,
		},
		{
			MethodName: "PatchFuturePodStatus",
			Handler:    _Fakekubelet_PatchFuturePodStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fakekubelet.proto",
}
